// data.jsx — design tokens, bilingual strings, and sample data for the prototype.
// All globals are hung off `window` so other Babel <script> tags can read them.

const TOKENS = {
  // Dark Minimal — slate background, calm whitespace, green primary
  ink:        '#F9FAFB',     // primary text
  inkSoft:    '#F3F4F6',
  paper:      '#0A0E17',     // page background (deeper — more depth + contrast)
  surface:    '#161F2C',     // cards (sit above the darker page)
  surfaceAlt: '#1E2A39',     // featured / inset
  border:     '#2F3A47',
  borderSoft: '#252F3A',
  muted:      '#9CA3AF',     // secondary text
  faint:      '#4B5563',
  accent:     '#16A34A',     // primary button green
  accentDeep: '#11833A',
  accentSoft: '#0E2A1A',
  green:      '#22C55E',     // success
  greenDeep:  '#16A34A',
  greenSoft:  '#0E3022',
  amber:      '#F59E0B',     // warning
  amberSoft:  '#3A2A0E',
  red:        '#EF4444',     // error
  redSoft:    '#3A1A1C',
  accentBright: '#22C55E',   // brighter green for gradients + glow
  // Elevation + glow — applied via boxShadow
  shadowSm:   '0 6px 18px -8px rgba(0,0,0,0.55)',
  shadowMd:   '0 18px 44px -16px rgba(0,0,0,0.60)',
  shadowLg:   '0 30px 70px -22px rgba(0,0,0,0.66)',
  glow:       '0 10px 28px -6px rgba(34,197,94,0.50)',
};

const I18N = {
  fr: {
    dir: 'ltr',
    locale: 'fr-DZ',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
    // url pill
    urlPill: 'barberdz.com/fade-city',
    // salon landing
    salonName: 'Fade City',
    salonTag: 'Coiffeur · Alger Centre',
    salonAddr: '12 Rue Didouche Mourad · Alger',
    salonAbout: 'Maison de coiffure indépendante. Sans rendez-vous depuis 2019. Réservez votre tour, on vous prévient quand c\'est bientôt.',
    openNow: 'Ouvert · ferme à 19h00',
    rating: '4,8',
    reviews: '212 avis',
    bookCta: 'Réserver mon tour',
    back: 'Retour',
    notifTurn: 'C’est bientôt votre tour — restez à proximité',
    keepBooking: 'Garder',
    confirmCancel: 'Confirmer l’annulation',
    bookingCancelled: 'Réservation annulée',
    bookingCancelledSub: 'Votre place dans la file a été libérée.',
    // Simpler step indicator
    stepOf: (i, total) => `Étape ${i} sur ${total}`,
    // pick barber friendly status
    freeNowFriendly: 'Libre tout de suite',
    waitTextShort: (m) => `Attendre environ ${m} min`,
    inSessionWait: (m, q) => `${q} avant vous · environ ${m} min`,
    breakBack: (m) => `Revient dans environ ${m} min`,
    chooseHimVerb: 'Choisir',
    // time picker friendly
    soonestTitle: 'Au plus tôt',
    inMin: (m) => `dans ${m} min`,
    inHourMin: (h, m) => m ? `dans ${h}h${String(m).padStart(2,'0')}` : `dans ${h}h`,
    timeTaken: 'Déjà réservé',
    seeMoreTimes: 'Voir plus d’horaires',
    servicePickerLabel: 'Prestation',
    chooseAnotherService: 'Choisir une autre prestation',
    // step labels
    stepBarber: 'Coiffeur',
    stepTime: 'Heure',
    stepDetails: 'Vos infos',
    stepDone: 'Confirmé',
    // pick barber
    pickBarberTitle: 'Choisissez votre coiffeur',
    pickBarberSub: 'La plupart de nos clients ont un favori.',
    freeNow: 'Libre maintenant',
    available: 'Disponible',
    inSession: 'En session',
    onBreak: 'En pause',
    waitMin: 'min d\'attente',
    inQueue: 'en attente',
    backInMin: 'retour dans',
    // pick time
    pickTimeTitle: 'Choisissez une heure',
    pickTimeSub: 'Choisissez la prestation, puis l’heure.',
    today: 'Aujourd\'hui',
    tomorrow: 'Demain',
    weekday: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
    morning: 'Matin',
    afternoon: 'Après-midi',
    evening: 'Soir',
    booked: 'Pris',
    // details
    detailsTitle: 'Votre nom et numéro',
    detailsSub: 'Pour que le coiffeur sache qui vous êtes.',
    fullName: 'Nom complet',
    namePlaceholder: 'Ahmed Benali',
    phone: 'Téléphone',
    phonePlaceholder: '551 23 45 67',
    privacy: 'Votre numéro n’est partagé qu’avec votre coiffeur pour gérer la file.',
    confirm: 'Confirmer la réservation',
    // done
    doneTitle: 'C’est fait !',
    doneSub: 'Votre place est réservée.',
    waitsAt: (name, time) => `${name} vous attend à ${time}`,
    showThisScreen: 'Montrez cet écran à votre arrivée.',
    yourNumber: 'Votre numéro',
    syncedToBarber: 'Envoyé à',
    bookingCode: 'Code de réservation',
    yourBarber: 'Votre coiffeur',
    at: 'à',
    addToCal: 'Ajouter au calendrier',
    viewQueue: 'Voir ma place dans la file',
    bookAgain: 'Faire une autre réservation',
    // queue tracker
    queueTitle: 'Votre file d\'attente',
    queuePos: 'Votre position',
    peopleBefore: (n) => n === 1 ? '1 personne avant vous' : `${n} personnes avant vous`,
    estWait: 'Attente estimée',
    youreNext: 'C\'est presque votre tour',
    soonAr: 'قريب',
    nextSubtitle: 'Restez à proximité — on vous appelle d\'une minute à l\'autre.',
    doneStateTitle: 'Session terminée',
    doneStateSub: 'Merci pour votre visite. À bientôt à Fade City.',
    rateVisit: 'Évaluer la visite',
    cancelBooking: 'Annuler la réservation',
    livePill: 'En direct',
    updatedNow: 'Mis à jour à l\'instant',
    barberStatus: 'Coiffeur',
    // barber app
    barberAppDate: 'Mardi 26 mai',
    inSessionLabel: 'En session',
    nextUp: 'Suivant',
    upcoming: 'À venir',
    clientsToday: 'Clients',
    avgTime: 'Temps moyen',
    elapsed: 'En cours',
    waitingFor: 'Attente',
    start: 'Démarrer',
    finish: 'Terminer',
    skip: 'Passer',
    pause: 'Pause file',
    resume: 'Reprendre',
    walkIn: 'Walk-in',
    addWalkIn: 'Ajouter un client',
    completedToday: (n) => `Terminés aujourd’hui (${n})`,
    emptyQueueTitle: 'Aucun client en attente',
    emptyQueueSub: 'Vous êtes à jour. Les nouvelles réservations apparaîtront ici.',
    callCustomer: 'Appeler',
    // Row actions
    manageClient: 'Gérer ce client',
    rescheduleAction: 'Reporter',
    markNoShow: 'Marquer absent',
    cancelBookingAction: 'Annuler la réservation',
    closeSheet: 'Fermer',
    rescheduleTitle: 'Reporter le rendez-vous',
    rescheduleSub: 'Le client a appelé pour repousser. Choisissez de combien.',
    delayBy: (m) => m >= 60 ? `+${m / 60} h` : `+${m} min`,
    nextFree: 'Prochain créneau libre',
    rescheduledTo: 'Reporté à',
    cancelledLabel: 'Annulée',
    noShowLabel: 'Absent',
    undo: 'Annuler l’action',
    confirmCancelTitle: 'Annuler la réservation ?',
    confirmCancelSub: 'Le créneau sera libéré et le client retiré de la file.',
    keep: 'Garder',
    yesCancel: 'Oui, annuler',
    walkInNamePh: 'Nom du client',
    walkInServicePh: 'Service',
    walkInAdd: 'Ajouter à la file',
    walkInCancel: 'Annuler',
    walkInTitle: 'Ajouter un walk-in',
    walkInSub: 'Client venu sans réservation.',
    newTag: 'Nouveau',
    newBookingBanner: (n) => n === 1 ? '1 nouvelle réservation' : `${n} nouvelles réservations`,
    justNow: 'à l’instant',
    noShow: 'Absent',
    queuePausedBanner: 'File en pause — les nouveaux clients ne peuvent plus réserver.',
    pauseShortBanner: 'En pause · reprise dans',
    pauseOfflineBanner: 'Hors service · aucune nouvelle réservation',
    pausePanelTitle: 'Mettre la file en pause',
    pause15: '15 min',
    pause30: '30 min',
    pause60: '1 heure',
    pauseOffline: 'Hors service',
    pauseOfflineSub: 'Toute la journée',
    pauseCancel: 'Annuler',
    pauseEndedTitle: 'Pause terminée',
    pauseEndedSub: 'Il est temps de reprendre.',
    resumeNow: 'Reprendre maintenant',
    overTime: 'Dépassement',
    sessionEndedToast: 'Session terminée · +',
    confirmFinishTitle: 'Terminer la session ?',
    confirmFinishSub: (name, amount, dzd) => `Ajouter ${amount.toLocaleString('fr-FR')} ${dzd} au revenu d’aujourd’hui (${name}).`,
    confirmFinishKeep: 'Continuer',
    confirmFinishYes: 'Terminer',
    confirmSkipTitle: 'Passer ce client ?',
    confirmSkipReplaces: (skipped, next) => `${skipped} sera passé. ${next} prend sa place.`,
    confirmSkipNoNext: (skipped) => `${skipped} sera retiré de la file.`,
    confirmSkipKeep: 'Annuler',
    confirmSkipYes: 'Oui, passer',
    // Settings
    settingsTitle: 'Réglages',
    settingsClose: 'Fermer',
    sectionProfile: 'Profil',
    sectionLanguage: 'Langue',
    sectionRevenue: 'Revenus',
    profilePhoto: 'Photo',
    changePhoto: 'Changer la photo',
    removePhoto: 'Retirer',
    yourName: 'Votre nom',
    yourSpecialty: 'Spécialité',
    save: 'Enregistrer',
    revenueToday: 'Aujourd’hui',
    revenueWeek: 'Cette semaine',
    revenueMonth: 'Ce mois',
    revenueClients: 'clients',
    revenueBreakdown: 'Détail',
    acceptingBookings: 'Accepter les nouvelles réservations',
    acceptingBookingsSub: 'Quand désactivé, vous n’apparaissez plus disponible à la réservation.',
    bookingsClosedBanner: 'Vous n’acceptez plus de réservations',
    bookingsClosedSub: 'Réactivez quand vous êtes prêt.',
    bookingsClosedShort: 'Indisponible',
    estimatedFinish: 'Termine vers',
    suivantOn: 'Suivant',
    toastFinished: (amount, dzd) => `Session terminée · +${amount.toLocaleString('fr-FR')} ${dzd}`,
    toastSkipped: (name) => `${name} passé`,
    toastNoShow: (name) => `${name} marqué absent`,
    toastRescheduled: (name, time) => `${name} reporté à ${time}`,
    toastCancelled: (name) => `${name} annulé`,
    toastUndone: 'Action annulée',
    toastWalkInAdded: (name) => `${name} ajouté à la file`,
    // Late + VIP + notes
    lateBy: (m) => `En retard de ${m} min`,
    addNote: 'Ajouter une note',
    notePlaceholder: 'Coupe préférée, allergies, etc.',
    saveNote: 'Enregistrer',
    markVip: 'Régulier',
    unmarkVip: 'Retirer régulier',
    // Empty state celebration
    dayDoneTitle: 'Belle journée !',
    dayDoneSub: (count, amount, dzd) => `${count} clients servis pour ${amount.toLocaleString('fr-FR')} ${dzd}.`,
    dayProgressLabel: 'Journée',
    // Re-add from completed
    reAddToQueue: 'Re-ajouter à la file',
    revenueScreenTitle: 'Revenus',
    tabDay: 'Jour',
    tabWeek: 'Semaine',
    tabMonth: 'Mois',
    avgPerCut: 'Moyenne / coupe',
    hoursWorked: 'Heures travaillées',
    vsYesterday: 'vs hier',
    vsLastWeek: 'vs sem. dernière',
    vsLastMonth: 'vs mois dernier',
    breakdownByService: 'Par service',
    weekdaysShort: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
    dzd: 'DA',
    min: 'min',
    h: 'h',
    today2: 'aujourd\'hui',
  },
  ar: {
    dir: 'rtl',
    locale: 'ar-DZ',
    fontFamily: '"Cairo", "Inter", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
    urlPill: 'barberdz.com/fade-city',
    salonName: 'فايد سيتي',
    salonTag: 'حلاق · وسط الجزائر',
    salonAddr: '12 شارع ديدوش مراد · الجزائر',
    salonAbout: 'صالون حلاقة مستقل. منذ 2019 بدون موعد مسبق. احجز دورك ونحن نعلمك حين يقترب.',
    openNow: 'مفتوح · يغلق على 19:00',
    rating: '4.8',
    reviews: '212 تقييم',
    bookCta: 'احجز دوري',
    back: 'رجوع',
    notifTurn: 'اقترب دورك — ابقَ قريباً',
    keepBooking: 'إبقاء',
    confirmCancel: 'تأكيد الإلغاء',
    bookingCancelled: 'أُلغي حجزك',
    bookingCancelledSub: 'تم تحرير مكانك في الطابور.',
    stepOf: (i, total) => `الخطوة ${i} من ${total}`,
    freeNowFriendly: 'متاح فوراً',
    waitTextShort: (m) => `حوالي ${m} د. انتظار`,
    inSessionWait: (m, q) => `${q} أمامك · حوالي ${m} د.`,
    breakBack: (m) => `يعود خلال ${m} د.`,
    chooseHimVerb: 'اختيار',
    soonestTitle: 'في أقرب وقت',
    inMin: (m) => `بعد ${m} د`,
    inHourMin: (h, m) => m ? `بعد ${h}سا${String(m).padStart(2,'0')}` : `بعد ${h}سا`,
    timeTaken: 'محجوز مسبقاً',
    seeMoreTimes: 'عرض أوقات أخرى',
    servicePickerLabel: 'الخدمة',
    chooseAnotherService: 'اختيار خدمة أخرى',
    stepBarber: 'الحلاق',
    stepTime: 'الوقت',
    stepDetails: 'معلوماتك',
    stepDone: 'تأكيد',
    pickBarberTitle: 'اختر حلاقك',
    pickBarberSub: 'لكل زبون حلاقه المفضل.',
    freeNow: 'متاح الآن',
    available: 'متاح',
    inSession: 'في جلسة',
    onBreak: 'في استراحة',
    waitMin: 'د. انتظار',
    inQueue: 'في الانتظار',
    backInMin: 'يعود خلال',
    pickTimeTitle: 'اختر الوقت',
    pickTimeSub: 'اختر الخدمة ثم الوقت.',
    today: 'اليوم',
    tomorrow: 'غداً',
    weekday: ['اث', 'ثل', 'أر', 'خم', 'جم', 'سب', 'أح'],
    morning: 'صباحاً',
    afternoon: 'ظهراً',
    evening: 'مساءً',
    booked: 'محجوز',
    detailsTitle: 'اسمك و رقمك',
    detailsSub: 'حتى يعرف الحلاق من أنت.',
    fullName: 'الاسم الكامل',
    namePlaceholder: 'أحمد بن علي',
    phone: 'الهاتف',
    phonePlaceholder: '551 23 45 67',
    privacy: 'رقمك يُشارك فقط مع الحلاق لإدارة القائمة.',
    confirm: 'تأكيد الحجز',
    doneTitle: 'تمّت !',
    doneSub: 'دورك محجوز.',
    waitsAt: (name, time) => `${name} ينتظرك على ${time}`,
    showThisScreen: 'أظهر هذه الشاشة عند الوصول.',
    yourNumber: 'رقمك',
    syncedToBarber: 'أُرسل إلى',
    bookingCode: 'رمز الحجز',
    yourBarber: 'حلاقك',
    at: 'على',
    addToCal: 'إضافة إلى التقويم',
    viewQueue: 'عرض مكاني في القائمة',
    bookAgain: 'حجز آخر',
    queueTitle: 'قائمة انتظارك',
    queuePos: 'موقعك',
    peopleBefore: (n) => n === 1 ? 'شخص واحد قبلك' : `${n} أشخاص قبلك`,
    estWait: 'الانتظار المتوقع',
    youreNext: 'دورك قريب',
    soonAr: 'قريب',
    nextSubtitle: 'ابقَ قريباً — سنناديك في أي لحظة.',
    doneStateTitle: 'انتهت الجلسة',
    doneStateSub: 'شكراً لزيارتك. إلى اللقاء في فايد سيتي.',
    rateVisit: 'قيّم الزيارة',
    cancelBooking: 'إلغاء الحجز',
    livePill: 'مباشر',
    updatedNow: 'محدث الآن',
    barberStatus: 'الحلاق',
    barberAppDate: 'الثلاثاء 26 ماي',
    inSessionLabel: 'في جلسة',
    nextUp: 'التالي',
    upcoming: 'قادم',
    clientsToday: 'زبائن',
    avgTime: 'معدل الوقت',
    elapsed: 'منذ',
    waitingFor: 'ينتظر',
    start: 'ابدأ',
    finish: 'إنهاء',
    skip: 'تخطي',
    pause: 'إيقاف الحجز',
    resume: 'استئناف',
    walkIn: 'بدون موعد',
    addWalkIn: 'إضافة زبون',
    completedToday: (n) => `انتهوا اليوم (${n})`,
    emptyQueueTitle: 'لا يوجد زبائن في الانتظار',
    emptyQueueSub: 'أنت على الجاهزية. الحجوزات الجديدة ستظهر هنا.',
    callCustomer: 'اتصل',
    // Row actions
    manageClient: 'إدارة هذا الزبون',
    rescheduleAction: 'تأجيل',
    markNoShow: 'تسجيل غياب',
    cancelBookingAction: 'إلغاء الحجز',
    closeSheet: 'إغلاق',
    rescheduleTitle: 'تأجيل الموعد',
    rescheduleSub: 'اتصل الزبون لتأجيل موعده. اختر المدة.',
    delayBy: (m) => m >= 60 ? `+${m / 60} سا` : `+${m} د`,
    nextFree: 'الموعد التالي المتاح',
    rescheduledTo: 'مؤجل إلى',
    cancelledLabel: 'ملغى',
    noShowLabel: 'غائب',
    undo: 'تراجع',
    confirmCancelTitle: 'إلغاء الحجز ؟',
    confirmCancelSub: 'سيتحرر الموعد و يُزال الزبون من القائمة.',
    keep: 'الإبقاء',
    yesCancel: 'نعم، إلغاء',
    walkInNamePh: 'اسم الزبون',
    walkInServicePh: 'الخدمة',
    walkInAdd: 'إضافة إلى القائمة',
    walkInCancel: 'إلغاء',
    walkInTitle: 'إضافة زبون بدون موعد',
    walkInSub: 'زبون جاء بدون حجز.',
    newTag: 'جديد',
    newBookingBanner: (n) => n === 1 ? 'حجز جديد' : `${n} حجوزات جديدة`,
    justNow: 'الآن',
    noShow: 'غائب',
    queuePausedBanner: 'الحجز متوقف — لا يمكن للزبائن الجدد الحجز.',
    pauseShortBanner: 'في إيقاف · يُستأنف بعد',
    pauseOfflineBanner: 'خارج الخدمة · لا حجوزات جديدة',
    pausePanelTitle: 'إيقاف القائمة',
    pause15: '15 د',
    pause30: '30 د',
    pause60: 'ساعة',
    pauseOffline: 'خارج الخدمة',
    pauseOfflineSub: 'لباقي اليوم',
    pauseCancel: 'إلغاء',
    pauseEndedTitle: 'انتهت الاستراحة',
    pauseEndedSub: 'حان وقت الاستئناف.',
    resumeNow: 'استئناف الآن',
    overTime: 'تجاوز',
    sessionEndedToast: 'انتهت الجلسة · +',
    confirmFinishTitle: 'إنهاء الجلسة ؟',
    confirmFinishSub: (name, amount, dzd) => `إضافة ${amount.toLocaleString('fr-FR')} ${dzd} إلى دخل اليوم (${name}).`,
    confirmFinishKeep: 'متابعة',
    confirmFinishYes: 'إنهاء',
    confirmSkipTitle: 'تخطي هذا الزبون ؟',
    confirmSkipReplaces: (skipped, next) => `${skipped} سيتم تخطيه. ${next} يأخذ مكانه.`,
    confirmSkipNoNext: (skipped) => `${skipped} سيُزال من القائمة.`,
    confirmSkipKeep: 'إلغاء',
    confirmSkipYes: 'نعم، تخطي',
    // Settings
    settingsTitle: 'الإعدادات',
    settingsClose: 'إغلاق',
    sectionProfile: 'الملف الشخصي',
    sectionLanguage: 'اللغة',
    sectionRevenue: 'الدخل',
    profilePhoto: 'الصورة',
    changePhoto: 'تغيير الصورة',
    removePhoto: 'إزالة',
    yourName: 'اسمك',
    yourSpecialty: 'التخصص',
    save: 'حفظ',
    revenueToday: 'اليوم',
    revenueWeek: 'هذا الأسبوع',
    revenueMonth: 'هذا الشهر',
    revenueClients: 'زبون',
    revenueBreakdown: 'التفصيل',
    acceptingBookings: 'قبول الحجوزات الجديدة',
    acceptingBookingsSub: 'عند الإيقاف، لن تظهر متاحاً للحجز.',
    bookingsClosedBanner: 'لم تعد تقبل الحجوزات',
    bookingsClosedSub: 'أعد التفعيل عندما تكون جاهزاً.',
    bookingsClosedShort: 'غير متاح',
    estimatedFinish: 'ينتهي حوالي',
    suivantOn: 'التالي',
    toastFinished: (amount, dzd) => `انتهت الجلسة · +${amount.toLocaleString('fr-FR')} ${dzd}`,
    toastSkipped: (name) => `تم تخطي ${name}`,
    toastNoShow: (name) => `${name} مسجل كغائب`,
    toastRescheduled: (name, time) => `${name} مؤجل إلى ${time}`,
    toastCancelled: (name) => `تم إلغاء ${name}`,
    toastUndone: 'تراجع',
    toastWalkInAdded: (name) => `تمت إضافة ${name} إلى القائمة`,
    // Late + VIP + notes
    lateBy: (m) => `متأخر بـ ${m} د`,
    addNote: 'إضافة ملاحظة',
    notePlaceholder: 'القصة المفضلة، حساسيات، إلخ.',
    saveNote: 'حفظ',
    markVip: 'زبون منتظم',
    unmarkVip: 'إلغاء منتظم',
    // Empty state celebration
    dayDoneTitle: 'يوم رائع !',
    dayDoneSub: (count, amount, dzd) => `${count} زبون خدمتهم بـ ${amount.toLocaleString('fr-FR')} ${dzd}.`,
    dayProgressLabel: 'اليوم',
    reAddToQueue: 'إعادة إلى القائمة',
    revenueScreenTitle: 'الدخل',
    tabDay: 'يوم',
    tabWeek: 'أسبوع',
    tabMonth: 'شهر',
    avgPerCut: 'متوسط القصة',
    hoursWorked: 'ساعات العمل',
    vsYesterday: 'مقارنة بالأمس',
    vsLastWeek: 'مقارنة بالأسبوع الماضي',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    breakdownByService: 'حسب الخدمة',
    weekdaysShort: ['إ', 'ث', 'أ', 'خ', 'ج', 'س', 'ح'],
    dzd: 'دج',
    min: 'د',
    h: 'سا',
    today2: 'اليوم',
  },
};

// ── Services menu (salon-wide pricing) ─────────────────────────────────
const SERVICES = [
  { id: 'coupe_adulte', price: 350,  duration: 30,
    name: { fr: 'Coupe adulte',                 ar: 'قصة للرجال' } },
  { id: 'coupe_enfant', price: 200,  duration: 20,
    name: { fr: 'Coupe enfant',                 ar: 'قصة طفل' } },
  { id: 'barbe',        price: 100,  duration: 10,
    name: { fr: 'Barbe',                        ar: 'لحية' } },
  { id: 'brushing',     price: 350,  duration: 25,
    name: { fr: 'Brushing',                     ar: 'بروشينغ' } },
  { id: 'coupe_barbe',  price: 450,  duration: 40,
    name: { fr: 'Coupe + barbe',                ar: 'قصة + لحية' } },
  { id: 'premium',      price: 1500, duration: 75,
    name: { fr: 'Protéine + coupe + brushing',  ar: 'بروتين + قصة + بروشينغ' } },
];

// ── Salon barbers ──────────────────────────────────────────────────────────
const BARBERS = [
  { id: 'karim', initials: 'KB',
    name: { fr: 'Karim Belkacem', ar: 'كريم بلقاسم' },
    specialty: { fr: 'Fade & dégradé', ar: 'تدرّج' },
    tint: '#EFE2C8', text: '#7A5B1F',
    state: 'free',         // free | queue | busy | break
    queueLen: 0, etaMin: 0, breakReturn: 0, price: 800,
  },
  { id: 'sofiane', initials: 'SH',
    name: { fr: 'Sofiane Hamidi', ar: 'سفيان حميدي' },
    specialty: { fr: 'Barbe & rasage', ar: 'لحية وحلاقة' },
    tint: '#D7E5DD', text: '#1F5A3F',
    state: 'queue', queueLen: 2, etaMin: 35, price: 1000,
  },
  { id: 'yacine', initials: 'YT',
    name: { fr: 'Yacine Touati', ar: 'ياسين تواتي' },
    specialty: { fr: 'Coupe moderne', ar: 'قصّة عصرية' },
    tint: '#E1DEEC', text: '#3D2F66',
    state: 'busy', queueLen: 3, etaMin: 55, price: 900,
  },
  { id: 'mehdi', initials: 'MO',
    name: { fr: 'Mehdi Ouazani', ar: 'مهدي وزاني' },
    specialty: { fr: 'Coupe classique', ar: 'قصّة كلاسيكية' },
    tint: '#EBDAD2', text: '#6A3825',
    state: 'break', queueLen: 1, etaMin: 15, breakReturn: 12, price: 700,
  },
];

// Time slots — 09:00 → 18:30, 30-min increments
const TIME_SLOTS = (() => {
  const s = [];
  for (let h = 9; h <= 18; h++) {
    s.push(`${String(h).padStart(2, '0')}:00`);
    s.push(`${String(h).padStart(2, '0')}:30`);
  }
  return s;
})();

const BOOKED_BY_DENSITY = {
  sparse: ['09:30', '11:00', '14:30', '16:00'],
  busy:   ['09:00','09:30','10:00','10:30','11:00','11:30','12:30','13:00','14:00','14:30','15:00','15:30','16:30','17:00','17:30'],
};

// Barber app queue
const QUEUE_BY_DENSITY = {
  sparse: [
    { id: 1, name: 'Ahmed B.',  phone: '0551 ** 12', time: '10:00', service: { fr: 'Fade',           ar: 'فيد' },          price: 800,  status: 'in_session', startedMinAgo: 6 },
    { id: 2, name: 'Yacine M.', phone: '0661 ** 47', time: '10:30', service: { fr: 'Coupe + barbe',  ar: 'قصة + لحية' },    price: 1500, status: 'waiting' },
    { id: 3, name: 'Walid A.',  phone: '0770 ** 03', time: '11:00', service: { fr: 'Fade',           ar: 'فيد' },          price: 800,  status: 'waiting' },
    { id: 4, name: 'Réda T.',   phone: '0552 ** 88', time: '11:30', service: { fr: 'Coupe classique',ar: 'قصة كلاسيكية' },  price: 700,  status: 'waiting' },
  ],
  busy: [
    { id: 1, name: 'Ahmed B.',  phone: '0551 ** 12', time: '10:00', service: { fr: 'Fade',          ar: 'فيد' },         price: 800,  status: 'in_session', startedMinAgo: 6 },
    { id: 2, name: 'Yacine M.', phone: '0661 ** 47', time: '10:30', service: { fr: 'Coupe + barbe', ar: 'قصة + لحية' },   price: 1500, status: 'waiting' },
    { id: 3, name: 'Walid A.',  phone: '0770 ** 03', time: '11:00', service: { fr: 'Fade',          ar: 'فيد' },         price: 800,  status: 'waiting' },
    { id: 4, name: 'Réda T.',   phone: '0552 ** 88', time: '11:30', service: { fr: 'Coupe',         ar: 'قصة' },          price: 700,  status: 'waiting' },
    { id: 5, name: 'Karim Z.',  phone: '0671 ** 54', time: '12:00', service: { fr: 'Fade + design', ar: 'فيد + رسم' },   price: 1200, status: 'waiting', walkIn: true },
    { id: 6, name: 'Hamza B.',  phone: '0775 ** 21', time: '12:30', service: { fr: 'Barbe',         ar: 'لحية' },         price: 500,  status: 'waiting' },
    { id: 7, name: 'Ilyas K.',  phone: '0553 ** 90', time: '13:00', service: { fr: 'Coupe enfant',  ar: 'قصة طفل' },      price: 600,  status: 'waiting' },
    { id: 8, name: 'Sami D.',   phone: '0664 ** 33', time: '13:30', service: { fr: 'Fade',          ar: 'فيد' },         price: 800,  status: 'waiting' },
    { id: 9, name: 'Adam L.',   phone: '0556 ** 71', time: '14:00', service: { fr: 'Coupe + barbe', ar: 'قصة + لحية' },   price: 1500, status: 'waiting', walkIn: true },
  ],
};

const COMPLETED_BY_DENSITY = {
  sparse: [{ name: 'Bilal K.', service: 'Fade', price: 800 }],
  busy:   [
    { name: 'Bilal K.',   service: 'Fade',          price: 800 },
    { name: 'Mounir S.',  service: 'Coupe',         price: 700 },
    { name: 'Tarek N.',   service: 'Coupe + barbe', price: 1500 },
    { name: 'Younes G.',  service: 'Fade + design', price: 1200 },
  ],
};

Object.assign(window, {
  TOKENS, I18N, BARBERS, SERVICES, TIME_SLOTS, BOOKED_BY_DENSITY,
  QUEUE_BY_DENSITY, COMPLETED_BY_DENSITY,
});
